##teamcity[testFailed duration='2' name='ExceptionTest.t1' details='|n	at ExceptionTest.t1(ExceptionTest.java:9)|n	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|n	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|n	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|n	at java.lang.reflect.Method.invoke(Method.java:497)|n	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)|n	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)|n	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)|n	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)|n	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)|n	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)|n	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)|n	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)|n	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)|n	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)|n	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)|n	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)|n	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)|n	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)|n	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)|n	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)|n	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)|n	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|n	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|n	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|n	at java.lang.reflect.Method.invoke(Method.java:497)|n	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)|n' error='true' message='java.lang.IllegalStateException: samebug test']
